language: java
sudo: required
jdk:
  - openjdk8
install: true
 
addons:
  sonarcloud:
    organization: "isaiasdias"
    secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  -- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=IsaiasDias_Enade
