language: java

jdk:
  - openjdk8

addons:
  sonarqube: true

script: 
  mvn clean verify sonar:sonar -Dsonar.login=423e74a53bf210c27735d92fbda8596c9398b0d8

notifications:
  email: isaiasferreiradias@gmail.com
