version: 2.1

jobs:
  
  build-and-test:  
  
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:  
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  main:
    jobs:
      -build:
        context: SonarCloud
  sample: 
    jobs:
      - build-and-test
