version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
    working_directory: /tmp
      - run:
          name: build & test
          command: mvn verify
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - persist_to_workspace:
          root: .
          paths:
            - target/*
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
  sonar:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: sonar
          command: mvn sonar:sonar

workflows:
  main:
    jobs:
      - build
      - sonar:
          context: SonarCloud
          requires:
            - build
